### ISSUE TITLE
Remove Controls from video player

### ISSUE THREAD

**Issue by dhruvPatel077** [Chris-Perkins/TwitchPlayer#1]
How can i remove all controls form Video player?

**Comment by Chris-Perkins** [comment]
Hi Dhruv,

Unfortunately, this is not possible with embedded players. Can you help me understand why you want to remove controls? Perhaps we can find a work-around.

If you simply want to prevent the user from clicking the player, you can make the player's `isUserInteractionEnabled` flag set to false.

**Comment by Chris-Perkins** [comment]
Closing due to lack of feedback; feel free to re-open this if your question remains.
